name: workflow

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: List files
      run: ls -la
    - name: Compile project
      run: CC=epiclang make
      timeout-minutes: 2